#!/usr/bin/php -q
<?php
require(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'Library/config.inc.php');

$parameter = $_SERVER["argv"];
array_shift($parameter);
$parameterClass = array_shift($parameter);

$consoleClassName = ucfirst($parameterClass) . '_console';

// C:\xampp\htdocs\cms\Library\Container\Extension\Cache\Cache.console.php

/** @var Console_abstract $console */
$console = new $consoleClassName(...
        $parameter);

$console->setOutputMode(Console_abstract::OUTPUT_MODE_CONSOLE);
$console->execute();

require_once(CMS_PATH_STORAGE_CACHE . '/class/console/console_' . $console->getConsoleID() . '.php');
$className = 'console_' . $console->getConsoleID();
new $className(Console_abstract::OUTPUT_MODE_CONSOLE);

exit();
?>
