#!/usr/bin/php -q
<?php
require(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'Library/config.inc.php');

$parameter = $_SERVER["argv"];
array_shift($parameter);

$parameterPrepare = implode(' ',
                            $parameter);

$parameterParsed = explode('::',
                           $parameterPrepare);

$consoleClassName = ucfirst(array_shift($parameterParsed)) . '_console';
$consoleMethod    = array_shift($parameterParsed);

/** @var Console_abstract $console */
$console = new $consoleClassName(0,
                                 $consoleMethod,
        ...
                                 $parameterParsed);

$console->setOutputMode(Console_abstract::OUTPUT_MODE_CONSOLE);
$console->execute();

require_once(CMS_PATH_STORAGE_CACHE . '/class/console/console_' . $console->getConsoleID() . '.php');
$className = 'console_' . $console->getConsoleID();
new $className(Console_abstract::OUTPUT_MODE_CONSOLE);

exit();
?>
